USE [master]
GO

/****** Object:  Database [UnitOfWorkExample]    Script Date: 2/25/2017 4:31:36 PM ******/
CREATE DATABASE [UnitOfWorkExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UnitOfWorkExample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\UnitOfWorkExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UnitOfWorkExample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\UnitOfWorkExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UnitOfWorkExample] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UnitOfWorkExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UnitOfWorkExample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET ARITHABORT OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UnitOfWorkExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UnitOfWorkExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UnitOfWorkExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UnitOfWorkExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UnitOfWorkExample] SET  MULTI_USER 
GO

ALTER DATABASE [UnitOfWorkExample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UnitOfWorkExample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UnitOfWorkExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UnitOfWorkExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UnitOfWorkExample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UnitOfWorkExample] SET QUERY_STORE = OFF
GO

USE [UnitOfWorkExample]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [UnitOfWorkExample] SET  READ_WRITE 
GO

